spring.application.name=frontend
server.port=3000

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# API Gateway URL
api.gateway.url=http://localhost:8080

# ???????
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=0

# ???????????
logging.level.org.example.frontend=DEBUG